# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from flow.execution import execution_pb2 as flow_dot_execution_dot_execution__pb2


class ExecutionAPIStub(object):
    """ExecutionAPI is the API provided by the execution nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/flow.execution.ExecutionAPI/Ping',
                request_serializer=flow_dot_execution_dot_execution__pb2.PingRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.PingResponse.FromString,
                )
        self.GetAccountAtBlockID = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetAccountAtBlockID',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDResponse.FromString,
                )
        self.ExecuteScriptAtBlockID = channel.unary_unary(
                '/flow.execution.ExecutionAPI/ExecuteScriptAtBlockID',
                request_serializer=flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDResponse.FromString,
                )
        self.GetEventsForBlockIDs = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetEventsForBlockIDs',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsResponse.FromString,
                )
        self.GetTransactionResult = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetTransactionResult',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.FromString,
                )
        self.GetTransactionResultByIndex = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetTransactionResultByIndex',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionByIndexRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.FromString,
                )
        self.GetTransactionResultsByBlockID = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetTransactionResultsByBlockID',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionsByBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultsResponse.FromString,
                )
        self.GetRegisterAtBlockID = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetRegisterAtBlockID',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDResponse.FromString,
                )
        self.GetLatestBlockHeader = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetLatestBlockHeader',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetLatestBlockHeaderRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.FromString,
                )
        self.GetBlockHeaderByID = channel.unary_unary(
                '/flow.execution.ExecutionAPI/GetBlockHeaderByID',
                request_serializer=flow_dot_execution_dot_execution__pb2.GetBlockHeaderByIDRequest.SerializeToString,
                response_deserializer=flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.FromString,
                )


class ExecutionAPIServicer(object):
    """ExecutionAPI is the API provided by the execution nodes.
    """

    def Ping(self, request, context):
        """Ping is used to check if the access node is alive and healthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountAtBlockID(self, request, context):
        """Accounts

        GetAccountAtBlockID gets an account by address at the given block ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScriptAtBlockID(self, request, context):
        """Scripts

        ExecuteScriptAtBlockID executes a ready-only Cadence script against the
        execution state at the block with the given ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventsForBlockIDs(self, request, context):
        """Events

        GetEventsForBlockIDs retrieves events for all the specified block IDs that
        have the given type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionResult(self, request, context):
        """Transaction

        GetTransactionResult gets the result of a transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionResultByIndex(self, request, context):
        """GetTransactionResultByIndex gets the result of a transaction at the index .
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionResultsByBlockID(self, request, context):
        """GetTransactionResultByIndex gets the results of all transactions in the
        block ordered by transaction index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisterAtBlockID(self, request, context):
        """Registers

        GetRegisterAtBlockID collects a register at the block with the given ID (if
        available).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestBlockHeader(self, request, context):
        """Block headers

        GetLatestBlockHeader gets the latest sealed or unsealed block header.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockHeaderByID(self, request, context):
        """GetBlockHeaderByID gets a block header by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.PingRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.PingResponse.SerializeToString,
            ),
            'GetAccountAtBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountAtBlockID,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDResponse.SerializeToString,
            ),
            'ExecuteScriptAtBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptAtBlockID,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDResponse.SerializeToString,
            ),
            'GetEventsForBlockIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventsForBlockIDs,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsResponse.SerializeToString,
            ),
            'GetTransactionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionResult,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.SerializeToString,
            ),
            'GetTransactionResultByIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionResultByIndex,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionByIndexRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.SerializeToString,
            ),
            'GetTransactionResultsByBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionResultsByBlockID,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetTransactionsByBlockIDRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetTransactionResultsResponse.SerializeToString,
            ),
            'GetRegisterAtBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisterAtBlockID,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDResponse.SerializeToString,
            ),
            'GetLatestBlockHeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestBlockHeader,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetLatestBlockHeaderRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'GetBlockHeaderByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockHeaderByID,
                    request_deserializer=flow_dot_execution_dot_execution__pb2.GetBlockHeaderByIDRequest.FromString,
                    response_serializer=flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flow.execution.ExecutionAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutionAPI(object):
    """ExecutionAPI is the API provided by the execution nodes.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/Ping',
            flow_dot_execution_dot_execution__pb2.PingRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountAtBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetAccountAtBlockID',
            flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetAccountAtBlockIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScriptAtBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/ExecuteScriptAtBlockID',
            flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.ExecuteScriptAtBlockIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventsForBlockIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetEventsForBlockIDs',
            flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetEventsForBlockIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransactionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetTransactionResult',
            flow_dot_execution_dot_execution__pb2.GetTransactionResultRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransactionResultByIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetTransactionResultByIndex',
            flow_dot_execution_dot_execution__pb2.GetTransactionByIndexRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetTransactionResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransactionResultsByBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetTransactionResultsByBlockID',
            flow_dot_execution_dot_execution__pb2.GetTransactionsByBlockIDRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetTransactionResultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRegisterAtBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetRegisterAtBlockID',
            flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.GetRegisterAtBlockIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestBlockHeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetLatestBlockHeader',
            flow_dot_execution_dot_execution__pb2.GetLatestBlockHeaderRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockHeaderByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.execution.ExecutionAPI/GetBlockHeaderByID',
            flow_dot_execution_dot_execution__pb2.GetBlockHeaderByIDRequest.SerializeToString,
            flow_dot_execution_dot_execution__pb2.BlockHeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
