# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from flow.executiondata import executiondata_pb2 as flow_dot_executiondata_dot_executiondata__pb2


class ExecutionDataAPIStub(object):
    """ExecutionDataAPI is the API for providing Execution state sync data, currently from Access Nodes
    ExecutionState
    GetExecutionDataByBlockID returns the execution_data object. Currently for
    use by the archive node to update its execution state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExecutionDataByBlockID = channel.unary_unary(
                '/flow.access.ExecutionDataAPI/GetExecutionDataByBlockID',
                request_serializer=flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDResponse.FromString,
                )


class ExecutionDataAPIServicer(object):
    """ExecutionDataAPI is the API for providing Execution state sync data, currently from Access Nodes
    ExecutionState
    GetExecutionDataByBlockID returns the execution_data object. Currently for
    use by the archive node to update its execution state.
    """

    def GetExecutionDataByBlockID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionDataAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExecutionDataByBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutionDataByBlockID,
                    request_deserializer=flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDRequest.FromString,
                    response_serializer=flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flow.access.ExecutionDataAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutionDataAPI(object):
    """ExecutionDataAPI is the API for providing Execution state sync data, currently from Access Nodes
    ExecutionState
    GetExecutionDataByBlockID returns the execution_data object. Currently for
    use by the archive node to update its execution state.
    """

    @staticmethod
    def GetExecutionDataByBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.ExecutionDataAPI/GetExecutionDataByBlockID',
            flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDRequest.SerializeToString,
            flow_dot_executiondata_dot_executiondata__pb2.GetExecutionDataByBlockIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
